const TEST_LYRIC_3 = {
  title: 'Finnegan\'s Wake',
  artist: 'The Dubliners',
  lines: [
    'Ah Tim Finnegan lived in Walkin Street',
    'A gentleman Irish mighty odd',
    'Well, he had a tongue both rich and sweet',
    'An\' to rise in the world he carried a hod',
    'Ah but Tim had a sort of a tipplin\' way',
    'With the love of the liquor he was born',
    'An\' to send him on his way each day',
    'He\'d a drop of the craythur every morn',
    'Whack fol the dah will ya dance to yer partner',
    'Around the flure yer trotters shake',
    'Wasn\'t it the truth I told you?',
    'Lots of fun at Finnegan\'s Wake',
    'One morning Tim was rather full',
    'His head felt heavy which made him shake',
    'He fell off the ladder and he broke his skull',
    'And they carried him home his corpse to wake',
    'Well they rolled him up in a nice clean sheet',
    'And they laid him out upon the bed',
    'With a bottle of whiskey at his feet',
    'And a barrel of porter at his head',
    'Whack fol the dah will ya dance to yer partner',
    'Around the flure yer trotters shake',
    'Wasn\'t it the truth I told you?',
    'Lots of fun at Finnegan\'s Wake',
    'Well his friends assembled at the wake',
    'And Mrs Finnegan called for lunch',
    'Well first they brought in tay and cake',
    'Then pipes, tobacco and brandy punch',
    'Then the widow Malone began to cry',
    '"Such a lovely corpse, did you ever see,',
    'Arrah, Tim avourneen, why did you die?"',
    '"Will ye hould your gob?" said Molly McGee',
    'Whack fol the dah will ya dance to yer partner',
    'Around the flure yer trotters shake',
    'Wasn\'t it the truth I told you?',
    'Lots of fun at Finnegan\'s Wake',
    'Well Mary O\'Connor took up the job',
    '"Biddy" says she "you\'re wrong, I\'m sure"',
    'Well Biddy gave her a belt in the gob',
    'And left her sprawling on the floor',
    'Well civil war did then engage',
    'T\'was woman to woman and man to man',
    'Shillelagh law was all the rage',
    'And a row and a ruction soon began',
    'Whack fol the dah will ya dance to yer partner',
    'Around the flure yer trotters shake',
    'Wasn\'t it the truth I told you?',
    'Lots of fun at Finnegan\'s Wake',
    'Well Tim Maloney raised his head',
    'When a bottle of whiskey flew at him',
    'He ducked, and landing on the bed',
    'The whiskey scattered over Tim',
    'Bedad he revives, see how he rises',
    'Tim Finnegan rising in the bed',
    'Saying "Whittle your whiskey around like blazes',
    'T\'underin\' Jaysus, do ye think I\'m dead?"',
    'Whack fol the dah will ya dance to yer partner',
    'Around the flure yer trotters shake',
    'Wasn\'t it the truth I told you?',
    'Lots of fun at Finnegan\'s Wake'
  ]
}

export default TEST_LYRIC_3;
