const TEST_LYRIC_JSON = {
  title: 'Fighting Against Conviction',
  artist: 'Bunny Wailer',
  lines: [
    'Battering down sentence, Fighting Against Convictions (2X)',
    'I find myself growing in an environment',
    'Where finding food is just as hard as paying the rent',
    'In trodding these roads of trials and tribulations',
    'I\'ve seen where some have died in desperation',
    'To keep battering down sentence, fighting against convictions (2X)',
    '',
    'In a family of ten and raised in the ghetto',
    'Hustling is the only education I know',
    'Can\'t grow no crops in this concrete jungle',
    'A situation like this is getting too hard to handle',
    'To keep battering down sentence, fighting against convictions (2X)',
    '',
    'With a pregnant woman, yes',
    'And five kids to care for',
    'Can\'t cool my heels, I\'ve got to do the town',
    'As skillful as I am, the jailer-man is bound to find me',
    'I pray the day will come when I shall be free from',
    'Battering down sentence, fighting against convictions (2X)',
    '',
    'To be trapped and caught and taken before judge and angry jury',
    'Pleading before men, who seem to have no mercy',
    'Can\'t afford to find myself down in the dungeons',
    'I\'ve got to stay free so that my kids won\'t be',
    'Battering down sentence, fighting against convictions (2X)',
    '',
    'Now a fugitive at large',
    'Could this be my destiny',
    'With no one to care for the wellfare of my family',
    'But in solitude I\'ve found new faith and hope in this I\'ll be secure',
    'For mind and soul would soon be weary',
    'Just couldn\'t take no more',
    'Battering down sentence, fighting against convictions'
  ]
}

export default TEST_LYRIC_JSON;
